# -*- coding: utf-8 -*-
"""Chap10 #16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cTMKm_GBK2ngdYrdcjgb_TpkXvlT_8b_
"""

#16. Write a program that converts a decimal height in feet into feet and inches. For instance, an input of 4.75 feet should become 4 feet, 9 inches.

def convert_height(height):
    feet = int(height)
    inches = round((height - feet) * 12)
    if inches == 12:
        feet += 1
        inches = 0
    return feet, inches

decimal_height = float(input("Enter height in feet: "))
feet, inches = convert_height(decimal_height)
print(f"{decimal_height} feet is equivalent to {feet} feet, {inches} inches.")