# -*- coding: utf-8 -*-
"""Chap10 #15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16JPPLHClhLE62V051wq9vKTl_2bYuw8u
"""

#15. Write a program to determine how many zeroes 1000! ends with.
def count_zeroes(n):
    count = 0
    while n >= 5:
        n //= 5
        count += n
    return count

num_zeroes = count_zeroes(1000)
print(num_zeroes)